quick fix
Maybe now


quick fix


self-hosted


self-hosted added properly


lol


probably fixed


fixed.


хватит


1


fix

diff --git a/.github/workflows/core_debug.yml b/.github/workflows/core_debug.yml
--- a/.github/workflows/core_debug.yml
+++ b/.github/workflows/core_debug.yml
@@ -7,7 +7,7 @@ on:
 
 env:
   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
-  BUILD_TYPE: DEBUG
+  BUILD_TYPE: Debug
 
 
 jobs:
@@ -20,14 +20,6 @@ jobs:
 
     steps:
       - uses: actions/checkout@v2
-      - uses: codecov/codecov-action@v1
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
-          files: ./coverage1.xml,./coverage2.xml # optional
-          flags: gtest, gcc # optional
-          name: codecov-umbrella # optional
-          fail_ci_if_error: true # optional (default = false)
-          verbose: true # optional (default = false)
 
       - name: Create Build Environment
         # Some projects don't allow in-source building, so create a separate build directory
@@ -35,7 +27,7 @@ jobs:
         run: cmake -E make_directory ${{github.workspace}}/build
 
       - name: Install dependencies
-        run: sudo apt-get install -y  libgtest-dev valgrind
+        run: sudo apt-get install -y libgtest-dev valgrind lcov
 
       - name: Configure CMake
         # Use a bash shell so we can use the same syntax for environment variable
@@ -45,7 +37,7 @@ jobs:
         # Note the current convention is to use the -S and -B options here to specify source
         # and build directories, but this is only available with CMake 3.13 and higher.
         # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
-        run: cmake ${{github.workspace}}/core/src -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCODE_COVERAGE=ON
+        run: cmake ${{github.workspace}}/core/src -DCMAKE_BUILD_TYPE=$BUILD_TYPE
 
       - name: Build tests
         working-directory: ${{github.workspace}}/build
@@ -64,12 +56,37 @@ jobs:
         working-directory: ${{github.workspace}}/build
         shell: bash
         # Execute the build.  You can specify a specific target with "--target <NAME>"
-        run: cmake --build . --config $BUILD_TYPE --target Laba2 -- -j $(nproc)
+        run: cmake --build . --config $BUILD_TYPE --target Laba2
 
       - name: Generate code coverage reports
-        working-directory: ${{github.workspace}}/build/CMakeFiles/Laba2.dir
+        working-directory: ${{github.workspace}}/build/Tests/CMakeFiles/Tests.dir
         shell: bash
         # Execute the build.  You can specify a specific target with "--target <NAME>"
-        run: gcov main.gcno
+#        run: gcov --xml main.gcno
+        run: |
+          lcov --directory . --capture --output-file coverage.info &&\
+          lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info &&\
+          lcov --list coverage.info &&\
+          bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
+
+
+#  - lcov --directory . --capture --output-file coverage.info
+#  # filter out system and extra files.
+#  # To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
+#  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
+#  # output coverage data for debugging (optional)
+#  - lcov --list coverage.info
+#  # Uploading to CodeCov
+#  # '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
+#  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
+
+#      - uses: codecov/codecov-action@v1
+#        with:
+#          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
+#          files: ./coverage1.xml,./coverage2.xml # optional
+#          flags: gtest, gcc # optional
+#          name: codecov-umbrella # optional
+#          fail_ci_if_error: true # optional (default = false)
+#          verbose: true # optional (default = false)
 
 
